import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiCircleStack,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiReactrouter,
  SiTailwindcss,
  SiBootstrap,
  SiNodedotjs,
  SiDotnet,
  SiPython,
  SiFastapi,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiGitlab,
  SiJira,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiLaravel,
  SiAdobexd,
  SiNestjs,
  SiMapbox,
  SiCss3,
  SiHtml5,
  SiGooglefonts,
  SiN8N,
  SiVite,
  SiOllama,
  SiSonarqube,
  SiEslint,
  SiPrettier,
  SiUml,
  SiSymfony

} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  reactrouter: SiReactrouter,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  nodejs: SiNodedotjs,
  dotnet: SiDotnet,
  python: SiPython,
  fastapi: SiFastapi,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  sqlserver: HiCircleStack,
  git: SiGit,
  gitlab: SiGitlab,
  jira: SiJira,
  taiga: HiOutlineRocketLaunch,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  laravel: SiLaravel,
  adobexd: SiAdobexd,
  nestjs: SiNestjs,
  mapbox: SiMapbox,
  css3: SiCss3,
  html5: SiHtml5,
  googleFont: SiGooglefonts,
  n8n: SiN8N,
  vite: SiVite,
  ollama: SiOllama,
  sonarQube: SiSonarqube,
  eslint: SiEslint,
  prettier: SiPrettier,
  uml: SiUml,
  symfony: SiSymfony
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
